name: Develop - Continuous Integration
run-name: ${{ github.actor }} has made changes 🚀
on: [ push ]

jobs:
  build-android:
    name: Test & Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Unit Test
        run: ./gradlew test
